export {
  assessGoal,
  fiNumber,
  futureValueLumpSum,
  futureValueSip,
  futureValueStepUpSip,
  monthsBetween,
  project,
  projectFi,
  projectTrajectory,
  realReturn,
  requiredSip,
  successProbability,
  suggestAllocation,
  type Allocation,
  type FiProjection,
  type GoalFeasibility,
  type TrajectoryPoint,
} from './projection';
